[versions]
jdk = "17" # min for jpackage
kotlin = "1.7.20"
ktor = "1.6.8"
exposed = "0.37.2"
ktfx = "0.1-SNAPSHOT"
prefs = "0.1-SNAPSHOT"
android-plugin = "7.3.1"
android-jdk = "8"
android-min = "14"
android-target = "32"
androidx = "1.5.0"
androidx-test = "1.4.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.6.1"
git-publish = "org.ajoberstar.git-publish:4.1.1"
localization = "com.hendraanggrian.localization:0.2"
generating = "com.hendraanggrian.generating:0.2"
packaging = "com.hendraanggrian.packaging:0.2"
pages = "com.hendraanggrian.pages:0.1"

[libraries]
# lint
ktlint = "com.pinterest:ktlint:0.48.1"
rulebook-ktlint = "com.hendraanggrian.rulebook:rulebook-ktlint:0.2-SNAPSHOT"
# main
kotlinx-coroutines-javafx = "org.jetbrains.kotlinx:kotlinx-coroutines-javafx:1.6.4"
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-gson = { module = "io.ktor:ktor-client-gson", version.ref = "ktor" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
ktfx-main = { module = "com.hendraanggrian.ktfx:ktfx", version.ref = "ktfx" }
ktfx-jfoenix = { module = "com.hendraanggrian.ktfx:jfoenix", version.ref = "ktfx" }
prefs-jvm = { module = "com.hendraanggrian.auto:prefs-jvm", version.ref = "prefs" }
prefs-android = { module = "com.hendraanggrian.auto:prefs-android", version.ref = "prefs" }
prefs-compiler = { module = "com.hendraanggrian.auto:prefs-compiler", version.ref = "prefs" }
sqlite-jdbc = "org.xerial:sqlite-jdbc:3.41.2.2"
maven-artifact = "org.apache.maven:maven-artifact:3.9.2"
commons-math3 = "org.apache.commons:commons-math3:3.6.1"
material = { module = "com.google.android.material:material", version.ref = "androidx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx" }
androidx-multidex = "androidx.multidex:multidex:2.0.1"
# test
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-junit = "androidx.test.ext:junit:1.1.3"
robolectric = "org.robolectric:robolectric:4.8.2"
truth = "com.google.truth:truth:1.1.3"

[bundles]
ktor-client = ["ktor-client-okhttp", "ktor-client-gson"]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc"]
ktfx = ["ktfx-main", "ktfx-jfoenix"]
androidx-test = ["androidx-test-core", "androidx-test-runner", "androidx-test-junit", "robolectric", "truth"]
